title: Ezenia Diaz-Lembert
logo: /assets/img/prof_pic.png
description: 
<p> Global R&D Consumer Systems and Architecture @ Bose </p>
<p> [Music](/music.md)</p>

show_downloads: false
theme: jekyll-theme-minimal
